site_name: APFly
pages:
- [index.md, Home]
- [getting_started.md, Getting Started]
- [api_reference.md, API Reference]
- [advanced_usage.md, Advanced Usage]
- [faq.md, FAQ]
- [demo.md, Demo]


theme: readthedocs
repo_url: https://github.com/jakobovski/apfly/
